//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FrontEnd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrontEnd() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("openPER.Resources.FrontEnd", typeof(FrontEnd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the main category from the side menu or directly from the car map..
        /// </summary>
        public static string CategorySelectBody {
            get {
                return ResourceManager.GetString("CategorySelectBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main category.
        /// </summary>
        public static string CategorySelectTitle {
            get {
                return ResourceManager.GetString("CategorySelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello and welcome to openPER.  This is an open source project to recreate the functonality of the FIAT ePER system.  The project is currently hosted at https://github.com/OldBoyCoder/openPER.
        /// </summary>
        public static string IntroParagraph {
            get {
                return ResourceManager.GetString("IntroParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogues.
        /// </summary>
        public static string MenuItemCatalogues {
            get {
                return ResourceManager.GetString("MenuItemCatalogues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string MenuItemGroups {
            get {
                return ResourceManager.GetString("MenuItemGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes.
        /// </summary>
        public static string MenuItemMakes {
            get {
                return ResourceManager.GetString("MenuItemMakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string MenuItemModels {
            get {
                return ResourceManager.GetString("MenuItemModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategories.
        /// </summary>
        public static string MenuItemSubGroups {
            get {
                return ResourceManager.GetString("MenuItemSubGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string MenuItemSubSubGroups {
            get {
                return ResourceManager.GetString("MenuItemSubSubGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vehicle was found matching the VIN.  If you feel your VIN should have been found and do not mind sharing that data then please contact us and we&apos;ll look into why it wasn&apos;t found.
        /// </summary>
        public static string VinNotFound {
            get {
                return ResourceManager.GetString("VinNotFound", resourceCulture);
            }
        }
    }
}
